# Generated by Django 3.1.5 on 2021-02-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210130_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_name',
            new_name='username',
        ),
    ]
